.TH KO "1"

.SH NAME

KO \- Computer Simulation of Dynamic Phenomena

.SH SYNOPSIS

To be determined

.SH DESCRIPTION

KO is a computer program for simulating phenomena in hydrodynamics, gas dynamics, and elastic plastic flow.

See "Wilkins, M.L. (1999). Computer Simulation of Dynamic Phenomena. Springer." for more information.
